version: "3"
services:
  node-app:
    build: .
    ports: 
      - "3000:3000"
    environment:
      - PORT=3000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tlgdn
      - MONGO_INITDB_ROOT_PASSWORD=tlgdn
    volumes:
      - mongo-db:/data/db


volumes:
  mongo-db: